services:
  - type: web
    name: billsplit
    runtime: node
    plan: free
    region: oregon
    buildCommand: npx pnpm install && npx pnpm run build
    startCommand: npx pnpm start
    envVars:
      - key: TOGETHER_API_KEY
        sync: false
      - key: S3_UPLOAD_KEY
        sync: false
      - key: S3_UPLOAD_SECRET
        sync: false
      - key: S3_UPLOAD_BUCKET
        sync: false
      - key: S3_UPLOAD_REGION
        value: us-east-1
      - key: HELICONE_API_KEY
        sync: false
